### ISSUE TITLE
メニューから遷移した場合と、詳細から戻った時でcssの効きかたが違ってる

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#231]
どのプラグインが原因かよくわからなかった。
報告まで。

http://127.0.0.1:9090/slug_videos
→効かない
![image](https://cloud.githubusercontent.com/assets/2756509/15451916/d054cf8e-2015-11e6-838b-81185b647ab9.png)

http://127.0.0.1:9090/videos/videos/index/27?frame_id=21
→効く
![image](https://cloud.githubusercontent.com/assets/2756509/15451922/0c99b338-2016-11e6-8dc2-ee806d80139e.png)

.\app\Plugin\NetCommons\webroot\css\style.css

``` css
/**
 * フレーム枠内
 */
.frame.nc-content header {
    margin-bottom: 16px;
}
```
