### ISSUE TITLE
連続する全角の！や半角英数字などを登録すると表示する際に折り返されず枠をはみ出る。

### ISSUE THREAD

**Issue by kitatsuw** [NetCommons3/NetCommons3#553]
![isuues02](https://cloud.githubusercontent.com/assets/17841377/17954193/375cebec-6ab4-11e6-85de-c894b6559700.png)

**Comment by akagane99** [comment]
css突っ込めば解決できるが、さてどうするかな。

``` css
body{
  word-wrap : break-word;
  overflow-wrap : break-word;
}
```

▼ word-breakとword-wrapはややこしい
https://w3g.jp/blog/confusing_word-break_word-wrap
