### ISSUE TITLE
セッションのクッキー名

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#700]
セッションのクッキー名が「CAKEPHP」となっているようだが、システム管理のセッション名を使うべき。

**Comment by s-nakajima** [comment]
Expireがおかしいのか、古いセッションが使われる場合がある。Session処理見直し。

**Comment by s-nakajima** [comment]
WYSWIYGのリンク切れが問題だった模様

**Comment by akagane99** [comment]
NC3.2.1.1で確認しました。
どうもうまくいってないようで、nccookieのクッキーは削除され、
CAKEPHPのクッキーが生きてます。

### login時のRespons Headers
```
HTTP/1.1 302 Found
Date: Wed, 02 Jan 2019 15:48:58 GMT
Server: Apache
Set-Cookie: nccookie=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/
Set-Cookie: CAKEPHP=olelliuf0gj0o07u05f8ngj2q3; expires=Wed, 02-Jan-2019 19:48:58 GMT; path=/; secure; HttpOnly
Set-Cookie: CAKEPHP=g6m0pquo1cqmtrmieg2ruhp9k4; expires=Wed, 02-Jan-2019 19:48:58 GMT; path=/; secure; HttpOnly
Location: https://mutaguchi.netcommons3.jp/private/3db57170308e0c5266a867295d4b0ff0
Content-Length: 0
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/html; charset=UTF-8
```

### クッキー名
![image](https://user-images.githubusercontent.com/2756509/50599587-da118800-0ef1-11e9-8a73-20cdf561a0ee.png)

**Comment by akagane99** [comment]
確認したところ、いつの間にかapplication.ymlにSession関係の設定が追加されてました。
前提は、常時httpsにしたからかなぁ。
ここの、  cookie:    session.name: を変えると、cookie名も変わりました。

app/Config/application.yml
```
Session:
  cookie: CAKEPHP
  timeout: 240
  ini:
    session.use_trans_sid: 0
    session.cookie_path: /
    session.cookie_lifetime: 14400
    session.name: CAKEPHP
    session.gc_maxlifetime: 14400
    session.cookie_httponly: 1
    session.cookie_secure: 1
  defaults: php
  cookieTimeout: 240
  cacheLimiter: must-revalidate
```

とりあえずここまで。
