### ISSUE TITLE
動画,Chromeの動画プレーヤーでダウンロードボタンが表示される

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#783]
Chromeの仕様変更により2016年年末位から、`<video>`タグの動画プレーヤーにダウンロードボタンが表示されるようになりました。
Chromeの仕様のため、現状対応策できてないです。

![default](https://cloud.githubusercontent.com/assets/2756509/21631455/c77327aa-d27e-11e6-9f3a-9e2bcdc75c41.PNG)

下記CSSのように、CSSでクロームのみボタンを非表示にできるといいのですが、ダウンロードボタンにあたるCSSの名前がわからないんだよなぁ。

```css
video::-webkit-media-controls-play-button {
    display: none;
}
```

### 補足

* IE11, Edge, FireFoxにはダウンロードボタン表示ない

### 参考リンク

http://www.w3schools.com/html/html5_video.asp
http://jsfiddle.net/wvtwLp0x/

**Comment by akagane99** [comment]
Chromeのエンジンはblink。
Chromeではなくchromiumだけど、blinkソースをのぞいてみた。
更新が1年4か月前と古かったため、欲しい情報がのってなかった。
https://chromium.googlesource.com/chromium/blink/+/master/Source/core/css/mediaControls.css

**Comment by akagane99** [comment]
下記cssでwindows chromeは対応できたけど、問題点も残っています。

```css
video::-webkit-media-controls-enclosure {
    overflow:hidden;
}

video::-webkit-media-controls-panel {
    width: calc(100% + 30px); /* Adjust as needed */
}
```
// media-controlsを30px大きくして、はみ出た所を非表示（結果、最右のダウンロードボタンが非表示）

2017-01-07時点のchrome55で下記は機能しませんでした。下記CSSだけで非表示になってほしいですね。
`video::-internal-media-controls-download-button {display:none;}`

### 問題点

* mac Safariで表示が変かも。
  * http://stackoverflow.com/questions/41115801/in-chrome-55-prevent-showing-download-button-for-html-5-video
  * > It may be a solution but looks like it may change more things than expected (ie: in Safari).
(機械翻訳) それは解決策かもしれませんが、予想より多くのものを変更する可能性があるようです（Safariでは）。
* Androidでchrome cast できると、ダウンロードボタン非表示が機能しない。
  * キャストボタンが最右に表示されるため、キャストボタンが消えてダウンロードボタンは残る
  * http://stackoverflow.com/questions/39602852/disable-download-button-for-google-chrome

chromiumのissueにも改善要求があがっていたので、次期アップデートとか様子を見た方がよさそうです。

### サンプル

http://jsfiddle.net/6ebLs316/

### 参考

chromiumのissueで改善要求が上がってました
https://bugs.chromium.org/p/chromium/issues/detail?id=675596&can=2&q=media%20download&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified
